rest:
  ssl: true
  host: api7.dspace.org
  port: 443
  nameSpace: /server

# UMD Customization
themes:
  - name: 'dspace'
  - name: 'mdsoar'
    extends: 'dspace'
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/mdsoar/images/favicons/favicon.ico
          sizes: any
  - name: 'mdsoar-frostburg'
    extends: 'mdsoar'
    handle: '11603/1'
  - name: 'mdsoar-goucher'
    extends: 'mdsoar'
    handle: '11603/2'
# End UMD Customization
