rest:
  ssl: true
  host: api7.dspace.org
  port: 443
  nameSpace: /server

# UMD Customization

# Disable End User Agreement
info:
  enableEndUserAgreement: false

themes:
  # Note: When placing themes into this list, any theme that "extends" from
  # another theme MUST appear before that theme in the list.

  # Community Themes
  - name: 'mdsoar-frostburg'
    extends: 'mdsoar'
    handle: '11603/1'

  - name: 'mdsoar-goucher'
    extends: 'mdsoar'
    handle: '11603/2'

  - name: 'mdsoar-hood'
    extends: 'mdsoar'
    handle: '11603/4380'

  - name: 'mdsoar-loyola-notre-dame'
    extends: 'mdsoar'
    handle: '11603/6'

  - name: 'mdsoar-morgan'
    extends: 'mdsoar'
    handle: '11603/8'

  - name: 'mdsoar-salisbury'
    extends: 'mdsoar'
    handle: '11603/9'

  - name: 'mdsoar-stevenson'
    extends: 'mdsoar'
    handle: '11603/4395'

  - name: 'mdsoar-st-marys'
    extends: 'mdsoar'
    handle: '11603/10'

  - name: 'mdsoar-towson'
    extends: 'mdsoar'
    handle: '11603/11'

  - name: 'mdsoar-ubalt'
    extends: 'mdsoar'
    handle: '11603/12'

  - name: 'mdsoar-umbc'
    extends: 'mdsoar'
    handle: '11603/14'

  - name: 'mdsoar-umes'
    extends: 'mdsoar'
    handle: '11603/27642'

  # MD-SOAR Global Theme
  - name: 'mdsoar'
    extends: 'dspace'
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/mdsoar/images/favicons/favicon.ico
          sizes: any

  # DSpace Stock theme
  - name: 'dspace'

# End UMD Customization
