rest:
  ssl: true
  host: api7.dspace.org
  port: 443
  nameSpace: /server

# UMD Customization
themes:
  # Note: When placing themes into this list, any theme that "extends" from
  # another theme MUST appear before that theme in the list.

  # Community Themes
  - name: 'mdsoar-frostburg'
    extends: 'mdsoar'
    handle: '11603/1'

  - name: 'mdsoar-goucher'
    extends: 'mdsoar'
    handle: '11603/2'

  # MD-SOAR Global Theme
  - name: 'mdsoar'
    extends: 'dspace'
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/mdsoar/images/favicons/favicon.ico
          sizes: any

  # DSpace Stock theme
  - name: 'dspace'
# End UMD Customization
